pipeline:
  name: testrelease
  identifier: testrelease
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Release
        identifier: clone
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Action
                  name: Checkout
                  identifier: Checkout
                  spec:
                    uses: actions/checkout@v2
                    with:
                      fetch-depth: "0"
              - step:
                  type: Action
                  name: Use Node JS
                  identifier: Use_Node_JS
                  spec:
                    uses: actions/setup-node@v1
                    with:
                      node-version: 16.x
                  failureStrategies: []
              - step:
                  type: Run
                  name: Lint and prettier check
                  identifier: Lint_and_prettier_check
                  spec:
                    connectorRef: harnessnew
                    image: node:16
                    shell: Sh
                    command: |-
                      yarn install
                      yarn lint
                      yarn tsc
                      yarn build
                      yarn prettier:check
              - step:
                  type: Run
                  name: npm publish
                  identifier: npm_publish
                  spec:
                    connectorRef: account.harnessImage
                    image: node:16
                    shell: Sh
                    command: |-
                      set -ex

                      # root build is required for
                      cd plugins/harness-feature-flags/
                      pwd
                      npm config set //registry.npmjs.org/:_authToken <+secrets.getValue("npm_token")>
                      yarn install
                      yarn tsc
                      yarn build
                      yarn add @changesets/cli && yarn changeset init
                      yarn changeset
                      yarn changeset version
                      # npm publish --verbose
                      yarn changeset publish --non-interactive

                      # publish only ci-cd plugins 
                      #cd plugins/harness-ci-cd/
                      # build gets triggered in prepublish step
                      #yarn publish --non-interactive
                    envVariables:
                      GIT_BOT_TOKEN: <+pipeline.variables.GIT_BOT_TOKEN>
                    resources:
                      limits:
                        memory: 8Gi
                        cpu: 2000m
                  when:
                    stageStatus: All
                  failureStrategies: []
              - step:
                  type: Action
                  name: changesets
                  identifier: Create_Release_Pull_Request_or_Publish_to_npm
                  id: changesets
                  spec:
                    uses: changesets/action@v1
                    with:
                      publish: yarn release
                    env:
                      CI: "true"
                      GITHUB_TOKEN: <+secrets.getValue("GITHUB_TOKEN")>
                      NPM_TOKEN: <+secrets.getValue("npm_token")>
                  when:
                    stageStatus: All
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: backstage-plugins
        build: <+input>
  variables:
    - name: GIT_BOT_TOKEN
      type: Secret
      value: account.githubbotharnesstoken
    - name: BOT_PASSWORD
      type: Secret
      value: account.githubbotharness
    - name: npm_token
      type: Secret
      value: <+secrets.getValue("npm_token")>
