apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  annotations:
    harness.io/cicd-accountIdentifier: <harness_account_id>
    harness.io/cicd-orgIdentifier: <harness_org_id>
    harness.io/cicd-projectIdentifier: <harness_project_id>
    harness.io/ci-pipelineIdentifiers: pipelineId1,pipelineId2,pipelineId3 
    harness.io/cd-serviceId: serviceId
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
