apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  annotations:
    # mandatory annotation
    harness.io/project-url: <harness_project_url>
    # optional annotations
    harness.io/application-map-tags: |
      <app-name_1>: <app-label_1>
      <app-name_2>: <app-label_2>
  tags:
    - java

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
